version: '3.9'

services:
  mongodb:
    build: ./mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ../data/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MONGO_DATABASE: telegram
      MONGO_USERNAME_FILE: /run/secrets/db_username
      MONGO_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_username
      - db_root_password
      - db_username
      - db_password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_SITE_BASEURL: /
      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/db_root_username
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/db_root_password
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/db_basicauth_password
    secrets:
      - db_root_username
      - db_root_password
      - db_basicauth_username
      - db_basicauth_password
    depends_on:
      - mongodb

secrets:
  db_root_username:
    file: mongodb/.db_root_username
  db_root_password:
    file: mongodb/.db_root_password
  db_username:
    file: mongodb/.db_username
  db_password:
    file: mongodb/.db_password
  db_basicauth_username:
    file: mongodb/.db_basicauth_username
  db_basicauth_password:
    file: mongodb/.db_basicauth_password